project_id = "igqtsjpbkjhvlliuhpcw"

[functions.generate-image]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.job-websocket]
verify_jwt = false

[functions.moderate-content]
verify_jwt = false
